version: '3.8'

services:
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    networks:
      - backend

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
      - backend
    expose:
      - "3306"  # Expose Port nur im internen Netzwerk

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - backend

  nodejs-api:
    image: m169-lb3-2024/nodejs:latest  # Die API-Software von Github
    networks:
      - backend
    depends_on:
      - mysql

networks:
  backend:
    driver: bridge
